### ISSUE TITLE
关于校准的问题

### ISSUE THREAD

**Issue by zbcUN** [NEU-REAL/REAL_DRONE_400#1]
您好 非常感谢您的工作，他对我非常有帮助。但是我的雷达和相机安装位置与您的不同，需要注意哪些校准问题吗？ 此外我看到视频里egoplaner的避障用到的像是激光雷达。在这个项目里面realsense是否有用到？

**Comment by TheConquerK** [comment]
你好，感谢你的对项目的肯定。在这个问题中，校准即外参标定是肯定需要的，我们现在的坐标系是以雷达的IMU为Body系建立的，和飞控IMU以及Realsense立体相机均存在一个静态的TF变换，这个变换矩阵可以通过我们提供的STEP模型直接计算，或者我们推荐使用Kalibr框架进行精确的外参标定，精确的外参会在项目的后续更新中给出。
