### ISSUE TITLE
轨迹跟踪效果比较差

### ISSUE THREAD

**Issue by zbcUN** [NEU-REAL/REAL_DRONE_400#2]
我的飞机是用的450机架，是这个算法，超调现象有点严重，经常会撞到周围物体。请问您有什么建议吗？

**Comment by TheConquerK** [comment]
450机架的配套动力套机动性是比较差的，px4_ctrl的PID参数需要重新整定。

**Comment by TheConquerK** [comment]
450机架的配套动力套机动性是比较差的，px4_ctrl的PID参数需要重新整定。
可以尝试如下步骤：
1. 飞机定点模式起飞
2. 调整 src/realflight_modules/px4ctrl/config/ctrl_param_fpv.yaml 中的
三轴PD参数
 gain: 
    # Cascade PID controller. Recommend to read the code.
    Kp0: 2.0
    Kp1: 2.0 
    Kp2: 2.0
    Kv0: 1.5
    Kv1: 1.5
    Kv2: 1.5
3.在飞行模式下微调后载入
rospram load ctrl_param_fpv.yaml
4.使用遥控器改变悬停点查看控制器效果，使用QGC观察控制效果，输出为目标点与实际位置曲线

注意：这种调试方法有一定风险，需要有熟练的飞手救机，在载入参数之前确保修改参数不会过大，且相对合理

**Comment by TheConquerK** [comment]
如果有效果可以给我反馈，之后我会关闭这个问题

**Comment by zbcUN** [comment]
好的等我飞机修好后调试给您反馈，
我还有一个问题想请教，我们电机用的2250kv的tmotorf60.我们的飞机有2.5kg重。电池是5200mah。续航时间非常短。是电机的问题吗？换成您项目里kv1100点tmotor是否会有改进？

**Comment by TheConquerK** [comment]
无人机太重了，动力套负载不太够，建议更换

**Comment by zbcUN** [comment]
您好 我的无人机修好了  我尝试了定点模式，前后左右飞在速度不快的情况下还算稳 但是上下很不稳  上下会一直震荡，您有什么建议吗，现在您发的那些值改成了  3 3 3 2 2 2

**Comment by zbcUN** [comment]
谢谢您的建议。我拆掉了深度相机。拆掉了电脑的外壳 现在整机算电池重量在1.89kg。根据淘宝上的参数我的四个电机应该有6104g推力。可是在起飞后的悬停阶段还是会上下震荡。但是在cmd模式不会抖动。也就是给定目标点后飞机z轴不会震荡。着有可能是什么原因呢？您是否有碰到过类似情况。

**Comment by TheConquerK** [comment]
尝试调整z轴参数应该能够解决，之前我有遇到过，不过基本上就是参数的问题。

**Comment by zbcUN** [comment]
您好，我参数还是调的毫无头绪，貌似它很难调，我又尝试开启了精准推力控制，在某些情况下是可以稳定的 但也有很多时候会突然无法起飞，例如电池刚刚冲满电时。
  同时我看见px4ctrl里面有一个精准推力控制校准的软件，但我没想明白它是如何使用。
