### ISSUE TITLE
Reject AUTO_TAKEOFF

### ISSUE THREAD

**Issue by ranjithlesoko** [NEU-REAL/REAL_DRONE_400#3]
[ INFO] [1709288461.395479347]: PX4CTRL] Waiting for RC
[ INFO] [1709288461.402635812]: [PX4CTRL] RC received.
[ INFO] [1709288462.613087580]: [px4ctrl] Voltage=4.826, percentage=1.000
[ERROR] [1709288468.683143015]: [px4ctrl] Reject AUTO_TAKEOFF. If you have your RC connected, keep its switches at "auto hover" and "command control" states, and all sticks at the center, then takeoff again.
if i remove rc_data.is_hover_mode  in line 100 it arm and  takeoff  
 i am using herelink how to set hover_mode to true

if ( !rc_data.is_command_mode || !rc_data.check_centered())
				{
					ROS_ERROR("[px4ctrl] Reject AUTO_TAKEOFF. If you have your RC connected, keep its switches at \"auto hover\" and \"command control\" states, and all sticks at the center, then takeoff again. is_hover_mode: %d, is_command_mode: %d, sticks_centered: %d", rc_data.is_hover_mode, rc_data.is_command_mode, rc_data.check_centered());

					while (ros::ok())
					{
						ros::Duration(0.01).sleep();
						ros::spinOnce();
						if (rc_data.is_hover_mode && rc_data.is_command_mode && rc_data.check_centered())
						{
							ROS_INFO("\033[32m[px4ctrl] OK, you can takeoff again.\033[32m");
							break;
						}
					}
					break;
				}

**Comment by TheConquerK** [comment]
Channel 6 is an enabled channel, with only two numerical values to distinguish. You can print out the assigned BOOL amount in the program to view it. Make sure that channel 6 enables the drone to take off automatically during automatic takeoff. If not, the error you are experiencing now will appear.

**Comment by ranjithlesoko** [comment]
@TheConquerK  if  i give this if ( !rc_data.is_command_mode || !rc_data.check_centered()) it get take off  i remove ! is_hover_mode  @TheConquerK  i cant find the logic  Channel 6   in  code

**Comment by TheConquerK** [comment]
You can check src/realflight_modules/px4ctrl/src/input.cpp AND find where channel 6 is used in this Program. Changing code is not recommanded.

**Comment by ranjithlesoko** [comment]
@TheConquerK  thanks

**Comment by ranjithlesoko** [comment]
issue fixed thanks @TheConquerK

**Comment by TheConquerK** [comment]
Okay. @ranjithlesoko
