### ISSUE TITLE
关于增加T265

### ISSUE THREAD

**Issue by zouqingxiao** [NEU-REAL/REAL_DRONE_400#4]
首先，非常感谢课题组开源资料助力国内自主无人机发展。有两个小问题请教：
1. 我计划拿掉激光雷达，换成T265做室内定位输出odom，这样就不用跑VIO或LIO了，机载端压力小一些。（因为我机载端还要跑神经网络）这种方式的定位方案靠得住么？感觉肯定比LIO差一些，不知道具体差多少？
2. 增加T265后我需要更改下安装板机械结构，有个问题是T265的FOV是163度，这样就会拍到桨叶，桨叶是不断旋转的，是否会影响定位精度？当前D435应该也会拍到桨叶吧？
![00](https://github.com/NEU-REAL/REAL_DRONE_400/assets/35356371/c438ed9e-82a0-4e89-83d8-50036514d0f1)

**Comment by TheConquerK** [comment]
1.我个人建议还是用激光好一点，其实 跑LIO耗费的资源不会特别大。T265我们没有在真机上测试过，但是手头是有传感器的，个人感觉T265的直出Odom在小范围，光照良好且纹理特征明显的环境是可以用的，但是不是特别推荐，毕竟是比较早之前的产品了，国内现在有类似的产品比如VIOBOT这种可以试试，似乎精度是足够的，也带有一个微处理器可以做一些功能。
2.在现在这种安装情况下，D435/D435i并不会出现桨叶干扰的情况，如果安装T265出现问题的话可以适当修改感知模块上板来满足你的设计需求
