### ISSUE TITLE
机载电脑的稳压模块

### ISSUE THREAD

**Issue by zouqingxiao** [NEU-REAL/REAL_DRONE_400#5]
吴博士，机载电脑的稳压模块用的哪款？能发个链接么

**Comment by TheConquerK** [comment]
LTC3780 
LINK: https://item.taobao.com/item.htm?_u=p3ovgp2s988d&id=537511849240&spm=a1z09.2.0.0.19c62e8dwykGML

**Comment by zouqingxiao** [comment]
感谢
