### ISSUE TITLE
how to connect NUC pc to Kakute H7

### ISSUE THREAD

**Issue by NamDinhRobotics** [NEU-REAL/REAL_DRONE_400#6]
Dear team,

I want to express my gratitude for providing such an excellent resource. I have a question regarding the connection of the Kakute H7 to a NUC PC. Could you please provide guidance on the different methods of connection and how to configure parameters in QGroundControl?

If possible, could you provide instructions on this topic using the following link: [Kakute H7 product page](https://holybro.com/products/kakute-h7)?

Thank you in advance for your assistance.

Best regards,

**Comment by TheConquerK** [comment]
Thank you for your recognition. In this project, NUC and Kakute mini H7 are connected via USB cable, using USB-A to USB-C wire. Parameters in QGroundControl are default.

**Comment by NamDinhRobotics** [comment]
Great work, thanks for your answer.
The connection is shown as follows, and we don't need to connect through TELEM1.
![connect](https://github.com/NEU-REAL/REAL_DRONE_400/assets/30413547/49d7d2ca-a9d5-40dd-a550-ebed514a695f)

After the connection, we don't need to change any parameters like EKF2 on PX4, and we can control the drone via Mavlink on the NUC. Is that correct?

Thanks so much for your help.
Bests,

**Comment by TheConquerK** [comment]
The correct connection is shown in your picture. There's no need to connect telem1 in this project , unless you need a radio for QGC. We don't change EKF2 parameters in PX4 flight controller as it's all used in Stablized mode rather than Position or Altitude. The position controller is adpated in onboard computer.

**Comment by NamDinhRobotics** [comment]
Great, thank you so much for your sharing,
Best wishes,
