### ISSUE TITLE
只用雷达时候 不显示近处障碍物

### ISSUE THREAD

**Issue by zbcUN** [NEU-REAL/REAL_DRONE_400#7]
您好。我发现只用雷达的时候无法显示近处的障碍物 经常发生碰撞这是正常的吗？

**Comment by TheConquerK** [comment]
这个问题可能与FAST-LIO中的雷达盲区配置有关，现有的雷达盲区配置为

**Comment by TheConquerK** [comment]
src/realflight_modules/mid360_fastlio/src/FAST_LIO/config/mid360.yaml

**Comment by TheConquerK** [comment]
这个问题可能与FAST-LIO中的雷达盲区配置有关，现有的雷达盲区配置为src/realflight_modules/mid360_fastlio/src/FAST_LIO/config/mid360.yaml line 11 blind参数，可以尝试把这个参数改小，并检查原始点云数据
