### ISSUE TITLE
项目中Mid360驱动编译失败

### ISSUE THREAD

**Issue by comi-zhang** [NEU-REAL/REAL_DRONE_400#8]
ubuntu环境下，上位机已连接mid360,git下来该项目后进行catkin_make,雷达驱动部分报错
![Uploading Screenshot from 2024-07-12 13-21-30.png…]()

**Comment by comi-zhang** [comment]
报错信息如下：
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_workspace.cmake:121 (add_subdirectory):
  The source directory

    /home/uav/REAL_DRONE_400-main/src/realflight_modules/mid360_fastlio/src/livox_ros_driver/livox_ros_driver

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)


-- +++ processing catkin package: 'fast_lio'
-- ==> add_subdirectory(realflight_modules/mid360_fastlio/src/FAST_LIO)
Current CPU archtecture: x86_64
Processer number:  16
core for MP: 3
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find livox_ros_driver (missing: livox_ros_driver_DIR)
-- Could not find the required component 'livox_ros_driver'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "livox_ros_driver"
  with any of the following names:

    livox_ros_driverConfig.cmake
    livox_ros_driver-config.cmake

  Add the installation prefix of "livox_ros_driver" to CMAKE_PREFIX_PATH or
  set "livox_ros_driver_DIR" to a directory containing one of the above
  files.  If "livox_ros_driver" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  realflight_modules/mid360_fastlio/src/FAST_LIO/CMakeLists.txt:45 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/uav/REAL_DRONE_400-main/build/CMakeFiles/CMakeOutput.log".
See also "/home/uav/REAL_DRONE_400-main/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by TheConquerK** [comment]
忽略报错，重复编译即可，catkin make还没编译到livox  ros driver

**Comment by wjw112211** [comment]
您好，我也遇到了相同的问题，重复编译是报错后继续catkin_make吗？这样试了好多次还是报错，请问改怎么解决呢？
